/* SPDX-License-Identifier: MIT
 *
 * Copyright (c) 2025, NVIDIA CORPORATION. All rights reserved.
 */

#ifndef __NVRM_CRASHCAT_H__
#define __NVRM_CRASHCAT_H__

/* Excerpt of nv-crashcat.h and libos_v3_crashcat.h from
 * https://github.com/NVIDIA/open-gpu-kernel-modules/tree/570.144
 */

#define NV_CRASHCAT_SIGNATURE				0xdead

#define NV_CRASHCAT_WAYFINDER_VERSION_1			1

#define NV_CRASHCAT_SCRATCH_GROUP_ID_NONE		0
#define NV_CRASHCAT_SCRATCH_GROUP_ID_A			1
#define NV_CRASHCAT_SCRATCH_GROUP_ID_B			2
#define NV_CRASHCAT_SCRATCH_GROUP_ID_C			3
#define NV_CRASHCAT_SCRATCH_GROUP_ID_D			4
#define NV_CRASHCAT_SCRATCH_GROUP_ID_E			5
#define NV_CRASHCAT_SCRATCH_GROUP_ID_F			6
#define NV_CRASHCAT_SCRATCH_GROUP_ID_IMPL_DEF		7

#define NV_CRASHCAT_MEM_APERTURE_SYSGPA			0
#define NV_CRASHCAT_MEM_APERTURE_FBGPA			1
#define NV_CRASHCAT_MEM_APERTURE_DMEM			2
#define NV_CRASHCAT_MEM_APERTURE_EMEM			3

#define NV_CRASHCAT_MEM_UNIT_SIZE_8B			0
#define NV_CRASHCAT_MEM_UNIT_SIZE_1KB			1
#define NV_CRASHCAT_MEM_UNIT_SIZE_4KB			2
#define NV_CRASHCAT_MEM_UNIT_SIZE_64KB			3

#define NV_CRASHCAT_PACKET_TYPE_REPORT			0x00
#define NV_CRASHCAT_PACKET_TYPE_RISCV64_CSR_STATE	0x01
#define NV_CRASHCAT_PACKET_TYPE_RISCV64_GPR_STATE	0x02
#define NV_CRASHCAT_PACKET_TYPE_RISCV64_TRACE		0x03
#define NV_CRASHCAT_PACKET_TYPE_IO32_STATE		0x04

#define NV_CRASHCAT_RISCV_MODE_UNSPECIFIED		0
#define NV_CRASHCAT_RISCV_MODE_M			1
#define NV_CRASHCAT_RISCV_MODE_S			2
#define NV_CRASHCAT_RISCV_MODE_U			3

#define NV_CRASHCAT_CONTAINMENT_UNSPECIFIED		0x0
#define NV_CRASHCAT_CONTAINMENT_RISCV_MODE_M		NV_CRASHCAT_RISCV_MODE_M
#define NV_CRASHCAT_CONTAINMENT_RISCV_MODE_S		NV_CRASHCAT_RISCV_MODE_S
#define NV_CRASHCAT_CONTAINMENT_RISCV_MODE_U		NV_CRASHCAT_RISCV_MODE_U
#define NV_CRASHCAT_CONTAINMENT_RISCV_HART		0x4
#define NV_CRASHCAT_CONTAINMENT_UNCONTAINED		0xF

#define NV_CRASHCAT_CAUSE_TYPE_EXCEPTION		0
#define NV_CRASHCAT_CAUSE_TYPE_TIMEOUT			1
#define NV_CRASHCAT_CAUSE_TYPE_PANIC			2

#define NV_CRASHCAT_TRACE_TYPE_STACK			0
#define NV_CRASHCAT_TRACE_TYPE_NVRVTB			1

#define NV_CRASHCAT_WAYFINDER_L0_SIGNATURE(l0)		((l0) & 0xffff)
#define NV_CRASHCAT_WAYFINDER_L0_VERSION(l0)		(((l0) >> 16) & 0xf)
#define NV_CRASHCAT_WAYFINDER_L0_V1_WFL1_LOCATION(l0)	(((l0) >> 20) & 0x7)
#define NV_CRASHCAT_WAYFINDER_L0_V1_WFL1_LOCATION_MASK	(0x7 << 20)

#define NV_CRASHCAT_WAYFINDER_L1_V1_QUEUE_APERTURE(l1)	((l1) & 0x7)
#define NV_CRASHCAT_WAYFINDER_L1_V1_QUEUE_UNIT_SIZE(l1)	(((l1) >> 3) & 0x3)
#define NV_CRASHCAT_WAYFINDER_L1_V1_QUEUE_SIZE(l1)	(((l1) >> 6) & 0xf)
#define NV_CRASHCAT_WAYFINDER_L1_V1_QUEUE_OFFSET(l1)	(((l1) >> 10) << 10)

#define NV_CRASHCAT_PACKET_HEADER_SIGNATURE(h)		((h) & 0xffff)
#define NV_CRASHCAT_PACKET_HEADER_FORMAT_VERSION(h)	(((h) >> 16) & 0xf)
#define NV_CRASHCAT_PACKET_HEADER_PAYLOAD_UNIT_SIZE(h)	(((h) >> 20) & 0x3)
#define NV_CRASHCAT_PACKET_HEADER_PAYLOAD_SIZE(h)	(((h) >> 22) & 0x3ff)
#define NV_CRASHCAT_PACKET_HEADER_V1_TYPE(h)		(((h) >> 32) & 0xff)
#define NV_CRASHCAT_PACKET_HEADER_V1_META(h)		((h) >> 40)

#define NV_CRASHCAT_REPORT_V1_IMPLEMENTER_SIGNATURE	0
#define NV_CRASHCAT_REPORT_V1_REPORTER_ID		8
#define NV_CRASHCAT_REPORT_V1_REPORTER_DATA		16
#define NV_CRASHCAT_REPORT_V1_SOURCE_ID			24
#define NV_CRASHCAT_REPORT_V1_SOURCE_CAUSE		32
#define NV_CRASHCAT_REPORT_V1_SOURCE_PC			40
#define NV_CRASHCAT_REPORT_V1_SOURCE_DATA		48
#define NV_CRASHCAT_REPORT_V1_SIZE			56

#define NV_CRASHCAT_REPORT_V1_ID_NVRISCV_PARTITION(id)	((id) & 0xff)
#define NV_CRASHCAT_REPORT_V1_ID_NVRISCV_UCODE_ID(id)	(((id) >> 8) & 0xff)
#define NV_CRASHCAT_REPORT_V1_ID_RISCV_MODE(id)		(((id) >> 16) & 0x7)
#define NV_CRASHCAT_REPORT_V1_ID_LIBOS3_TASK_ID(id)	(((id) >> 24) & 0xff)
#define NV_CRASHCAT_REPORT_V1_ID_LIBOS3_TASK_ID_UNSPECIFIED	0xff

#define NV_CRASHCAT_REPORT_V1_REPORTER_DATA_VERSION(d)	((d) & 0xffffffff)
#define NV_CRASHCAT_REPORT_V1_REPORTER_DATA_TIMESTAMP(d) ((d) >> 32)
#define NV_CRASHCAT_REPORT_V1_REPORTER_DATA_VERSION_LIBOS3_CL(v)	((v) & 0xffffff)
#define NV_CRASHCAT_REPORT_V1_REPORTER_DATA_VERSION_LIBOS3_MINOR(v)	(((v) >> 24) & 0xf)
#define NV_CRASHCAT_REPORT_V1_REPORTER_DATA_VERSION_LIBOS3_MAJOR(v)	(((v) >> 28) & 0xf)

#define NV_CRASHCAT_REPORT_V1_SOURCE_CAUSE_TYPE(c)	((c) & 0xf)
#define NV_CRASHCAT_REPORT_V1_SOURCE_CAUSE_CONTAINMENT(c) (((c) >> 4) & 0xf)
#define NV_CRASHCAT_REPORT_V1_SOURCE_CAUSE_LIBOS3_REASON(c) (((c) >> 32) & 0xff)

#define NV_CRASHCAT_REPORT_IMPLEMENTER_SIGNATURE_LIBOS3	0x4C49424F53332E31ull

#define NV_CRASHCAT_RISCV64_CSR_STATE_V1_XSTATUS	0
#define NV_CRASHCAT_RISCV64_CSR_STATE_V1_XIE		8
#define NV_CRASHCAT_RISCV64_CSR_STATE_V1_XIP		16
#define NV_CRASHCAT_RISCV64_CSR_STATE_V1_XEPC		24
#define NV_CRASHCAT_RISCV64_CSR_STATE_V1_XTVAL		32
#define NV_CRASHCAT_RISCV64_CSR_STATE_V1_XCAUSE		40
#define NV_CRASHCAT_RISCV64_CSR_STATE_V1_XSCRATCH	48
#define NV_CRASHCAT_RISCV64_CSR_STATE_V1_SIZE		56
#define NV_CRASHCAT_RISCV64_CSR_STATE_V1_HEADER_RISCV_MODE(m)	((m) & 0x7)

#define NV_CRASHCAT_RISCV64_GPR_STATE_V1_SIZE		248

#define NV_CRASHCAT_RISCV64_TRACE_V1_HEADER_RISCV_MODE(m)	((m) & 0x7)
#define NV_CRASHCAT_RISCV64_TRACE_V1_HEADER_TRACE_TYPE(m)	(((m) >> 3) & 0x1)

#define NV_CRASHCAT_IO32_STATE_V1_HEADER_APERTURE(m)	((m) & 0x3)

#define LIBOS_PANIC_REASON_UNSPECIFIED			0x00
#define LIBOS_PANIC_REASON_UNHANDLED_STATE		0x01
#define LIBOS_PANIC_REASON_INVALID_CONFIGURATION	0x02
#define LIBOS_PANIC_REASON_FATAL_HARDWARE_ERROR		0x03
#define LIBOS_PANIC_REASON_INSUFFICIENT_RESOURCES	0x04
#define LIBOS_PANIC_REASON_TIMEOUT			0x05
#define LIBOS_PANIC_REASON_ENV_CALL_FAILED		0x06
#define LIBOS_PANIC_REASON_ASAN_MEMORY_ERROR		0x08
#define LIBOS_PANIC_REASON_PROGRAMMING_ERROR		0x0a
#define LIBOS_PANIC_REASON_ASSERTION_FAILED		0x0b
#define LIBOS_PANIC_REASON_TRAP_KERNEL_PANIC		0x0c
#define LIBOS_PANIC_REASON_TRAP_INSTRUCTION		0x0d

#endif
